(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const catalog=JSON.parse($('#concept-catalog')?.textContent||'[]');
const shopify=document.body.dataset.shopify==='true';
const root=document.body.dataset.root||'/';
const money=v=>new Intl.NumberFormat(document.documentElement.lang||'en',{style:'currency',currency:document.body.dataset.currency||'USD'}).format(v/100);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cart=[]; try{cart=JSON.parse(localStorage.getItem('omnivert-demo-cart-v2')||'[]').filter(x=>catalog.some(p=>p.id===x.id)&&Number.isInteger(x.qty)&&x.qty>0&&x.qty<100)}catch{}
let activeProduct=null, selected='', qty=1, lastTrigger=null, liveProduct=null;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function headerPosition(){const h=$('.header');if(h)document.documentElement.style.setProperty('--header-bottom',h.getBoundingClientRect().bottom+'px')}
headerPosition();addEventListener('resize',headerPosition);addEventListener('scroll',headerPosition,{passive:true});
function closeMega(){const m=$('#mega'),s=$('#nav-shade');if(m)m.hidden=true;if(s)s.hidden=true;$$('[data-mega]').forEach(b=>b.setAttribute('aria-expanded','false'))}
function closeDialog(d,immediate=false){if(!d?.open)return;d.classList.add('closing');setTimeout(()=>{d.close();d.classList.remove('closing');if(lastTrigger?.isConnected)lastTrigger.focus({preventScroll:true})},immediate||reduced?0:180)}
function open(id){closeMega();$$('dialog[open]').forEach(d=>{d.close();d.classList.remove('closing')});lastTrigger=document.activeElement;headerPosition();const d=document.getElementById(id);if(d){d.showModal();if(id==='search')$('#search-input').focus();}if(id==='cart')renderCart()}
$$('dialog').forEach(d=>{d.querySelector('.close')?.addEventListener('click',()=>closeDialog(d));d.addEventListener('cancel',e=>{e.preventDefault();closeDialog(d)});d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(d)})});
function info(title,body){$('#info-title').textContent=title;$('#info-text').textContent=body;open('info')}
function infoFor(title){const copy={'Track my order':'Order tracking will connect to your Shopify customer account once the store launches. No real orders are accepted in this preview.','My account':'Customer login will connect to Shopify once the store is set up.','Contact':'The Omnivert contact details have not been provided yet. This area is reserved for the approved customer support information.','Privacy':'Omnivert’s privacy policy will be added before launch. This preview does not submit email addresses or load marketing trackers.','Terms':'The approved Omnivert terms will be added before launch.','Returns':'The returns policy has not been finalized. No return window or eligibility is promised in this preview.','Shipping':'Shipping destinations, rates and delivery times will be configured in Shopify before launch.','About this preview':'Original Omnivert design concepts with AI-generated imagery. Product names, sizes and artwork are for review; prices and availability are not finalized. Demo cart items stay in this browser. Checkout and newsletter signup are not connected.'};info(title,copy[title]||copy['About this preview'])}
function card(p){return `<article class="product-card" data-category="${esc(p.category)}" data-id="${p.id}"><div class="card-media"><a href="?product=${p.id}" data-detail="${p.id}" aria-label="View ${esc(p.name)}"><span class="art ${p.art}" role="img" aria-label="${esc(p.color+' '+p.name)} concept"></span><span class="model-view ${p.art}" role="img" aria-label="Model view of ${esc(p.name)}"></span></a><button class="model-toggle" data-model-toggle aria-label="Show model view" aria-pressed="false">ON MODEL</button><button class="quick" data-quick="${p.id}" aria-label="Choose options for ${esc(p.name)}"><span>CHOOSE OPTIONS</span><b>+</b></button></div><div class="card-copy"><a href="?product=${p.id}" data-detail="${p.id}">${esc(p.name)}</a><p>CONCEPT / PRICE TBC</p></div></article>`}
function filtered(category,query=''){return catalog.filter(p=>(category==='All'||category==='New arrivals'||p.category===category||p.capsule===category||p.edits?.includes(category)||(category==='Clothing'&&p.category==='Matching sets')||(category==='Accessories'&&p.category==='Bags'))&&(!query||(p.name+' '+p.color+' '+p.category+' '+(p.capsule||'')).toLowerCase().includes(query.toLowerCase())))}
function filter(category,query='',scroll=false){const grid=$('#product-grid');if(!grid){if(shopify){location.href=root+'search?q='+encodeURIComponent(query||category)+'&type=product';}return;}const items=filtered(category,query);grid.innerHTML=items.map(card).join('')||'<p class="empty">No matching products. Try another search.</p>';let selectedTab=null;$$('[data-tab]').forEach(t=>{const yes=t.dataset.tab===category;t.setAttribute('aria-selected',yes);t.tabIndex=yes?0:-1;if(yes)selectedTab=t});if(selectedTab){grid.setAttribute('aria-labelledby',selectedTab.id);grid.removeAttribute('aria-label')}else{grid.removeAttribute('aria-labelledby');grid.setAttribute('aria-label',query?'Search results for '+query:category)}if(scroll)$('#collection')?.scrollIntoView({behavior:reduced?'instant':'smooth'});closeMega();$$('dialog[open]').forEach(d=>closeDialog(d));}
function persist(){try{localStorage.setItem('omnivert-demo-cart-v2',JSON.stringify(cart))}catch{}updateCount()}
function updateCount(n){const el=$('#cart-count');if(!el)return;const total=n??cart.reduce((a,b)=>a+b.qty,0);el.textContent=total;el.hidden=!total}
function demoCart(){const list=$('#cart-items'),bottom=$('#cart-bottom');if(!cart.length){list.innerHTML='<p class="empty">Your cart is empty</p>';bottom.innerHTML='';return;}list.innerHTML=cart.map((line,i)=>{const p=catalog.find(p=>p.id===line.id);return `<div class="cart-line"><span class="art ${p.art}" role="img" aria-label="${esc(p.name)}"></span><div><h3>${esc(p.name)}</h3><p>${esc(p.color)} / ${esc(line.size)}</p><p>Concept · Price TBC</p><div class="quantity"><button data-cart-delta="-1" data-line="${i}" aria-label="Decrease ${esc(p.name)} quantity">−</button><output>${line.qty}</output><button data-cart-delta="1" data-line="${i}" aria-label="Increase ${esc(p.name)} quantity">+</button></div><button class="remove" data-remove="${i}">Remove</button></div></div>`}).join('');bottom.innerHTML='<p class="cart-note">Preview cart — items and sizes are concepts. No payment is collected.</p><button class="solid" data-demo-checkout>CHECKOUT — PREVIEW</button>';updateCount()}
async function renderCart(){if(!shopify){demoCart();return;}$('#cart-items').innerHTML='<p class="empty">Loading your cart…</p>';$('#cart-bottom').innerHTML='';try{const r=await fetch(root+'cart.js');if(!r.ok)throw Error();const c=await r.json();updateCount(c.item_count);$('#cart-items').innerHTML=c.items.length?c.items.map((p,i)=>`<div class="cart-line">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.title)}">`:''}<div><h3>${esc(p.product_title)}</h3><p>${esc(p.variant_title||'')}</p><p>${money(p.final_line_price)}</p><div class="quantity"><button data-live-line="${i+1}" data-live-qty="${p.quantity-1}" aria-label="Decrease ${esc(p.title)} quantity">−</button><output>${p.quantity}</output><button data-live-line="${i+1}" data-live-qty="${p.quantity+1}" aria-label="Increase ${esc(p.title)} quantity">+</button></div><button class="remove" data-live-line="${i+1}" data-live-qty="0">Remove</button></div></div>`).join(''):'<p class="empty">Your cart is empty</p>';$('#cart-bottom').innerHTML=c.items.length?`<p>SUBTOTAL ${money(c.total_price)}</p><p class="cart-note">Shipping and taxes calculated at checkout.</p><form action="${root}cart" method="post"><button name="checkout" class="solid">CHECKOUT</button></form>`:'';}catch{ $('#cart-items').innerHTML=`<p>Unable to load your cart.</p><a class="solid" href="${root}cart">OPEN CART PAGE</a>`;}}
function showProduct(id,detail=false){const p=catalog.find(x=>x.id===Number(id));if(!p)return;activeProduct=p;liveProduct=null;selected=p.sizes[0];qty=1;$('#quick-content').innerHTML=`<div class="quick-layout"><span class="art ${p.art}" role="img" aria-label="${esc(p.name)} concept"></span><div><h2>${esc(p.name)}</h2><p class="price">CONCEPT / PRICE TBC</p><p>${esc(p.color)}</p><p class="variant-label">Size: <span id="size-label">${selected}</span></p><div class="sizes">${p.sizes.map(s=>`<button data-size="${s}" aria-pressed="${s===selected}">${s}</button>`).join('')}</div><div class="quantity"><button data-qty="-1" aria-label="Decrease quantity">−</button><output id="quantity">1</output><button data-qty="1" aria-label="Increase quantity">+</button></div><button class="solid" data-add-concept>${shopify?'PREVIEW CONCEPT':'ADD TO CART — PREVIEW'}</button>${p.match ? `<p class="swim-pair">COMPLETE THE MATCH<br><a href="?product=${p.match}" data-detail="${p.match}">${esc(catalog.find(x=>x.id===p.match)?.name || "Matching swimwear")} ↗</a></p>` : ""}<p class="disclosure">Design study. Sizes are illustrative; final fit, materials and price to be confirmed.</p><details ${detail?'open':''}><summary>PRODUCT DETAILS</summary><p>${esc(p.description || (p.name+' in '+p.color.toLowerCase()+'. An original Omnivert '+p.category.toLowerCase()+' concept from the first collection study.'))}</p></details><details><summary>DELIVERY & RETURNS</summary><p>Not available to purchase yet. Delivery and returns will be confirmed before launch.</p></details></div></div>`;open('quick')}
async function showLiveProduct(url){activeProduct=null;liveProduct=null;$('#quick-content').innerHTML='<p class="empty">Loading product…</p>';open('quick');try{const r=await fetch(url.split('?')[0]+'.js');if(!r.ok)throw Error();const p=await r.json();liveProduct=p;const v=p.variants.find(v=>v.available)||p.variants[0];selected=String(v.id);qty=1;$('#quick-content').innerHTML=`<div class="quick-layout">${p.featured_image?`<img class="real-image" src="${esc(p.featured_image)}" alt="${esc(p.title)}">`:''}<div><h2>${esc(p.title)}</h2><p class="price" id="live-price">${money(v.price)}</p><p class="variant-label">Choose an option</p><div class="sizes">${p.variants.map(x=>`<button data-live-variant="${x.id}" aria-pressed="${x.id===v.id}" ${x.available?'':'disabled'}>${esc(x.public_title||x.title)}</button>`).join('')}</div><div class="quantity"><button data-qty="-1" aria-label="Decrease quantity">−</button><output id="quantity">1</output><button data-qty="1" aria-label="Increase quantity">+</button></div><button class="solid" data-add-live ${v.available?'':'disabled'}>${v.available?'ADD TO CART':'SOLD OUT'}</button><p id="product-error" role="status"></p><a class="detail-link" href="${esc(url)}">View full product details</a></div></div>`}catch{$('#quick-content').innerHTML=`<p>Unable to load product options.</p><a class="solid" href="${esc(url)}">VIEW PRODUCT</a>`}}
let searchTimer;$('#search-input')?.addEventListener('input',e=>{clearTimeout(searchTimer);const q=e.target.value.trim();if(shopify){$('#search-results').textContent=q?'Press Enter to search the store.':'';return;}searchTimer=setTimeout(()=>{$('#search-results').innerHTML=q?'<div class="search-results-grid">'+(filtered('All',q).slice(0,6).map(card).join('')||'<p>No results found.</p>')+'</div>':''},120)});
$('#search-form')?.addEventListener('submit',e=>{e.preventDefault();const q=$('#search-input').value.trim();if(shopify)location.href=root+'search?q='+encodeURIComponent(q)+'&type=product';else filter('All',q,true)});
$('#waitlist-form')?.addEventListener('submit',e=>{if(e.currentTarget.dataset.preview==='true'){e.preventDefault();$('#wait-status').textContent='Preview only — your email was not saved and no code was sent. Email delivery will be enabled when Shopify is connected.';return;}const button=e.currentTarget.querySelector('button[type=submit]');if(button){button.disabled=true;button.textContent='SUBMITTING…';}});
$('#waitlist [data-decline-offer]')?.addEventListener('click',()=>closeDialog($('#waitlist')));
const offerKey='omnivert-welcome-offer-v1';
function markOfferSeen(){try{localStorage.setItem(offerKey,String(Date.now()))}catch{}}
const offerDialog=$('#waitlist');offerDialog?.addEventListener('close',markOfferSeen);
if($('[data-offer-success]')){try{localStorage.setItem('omnivert-email-subscribed','true')}catch{}open('waitlist');}
else if($('[data-offer-error]'))open('waitlist');
else {let offerTimer;function scheduleOffer(){clearTimeout(offerTimer);if(document.hidden)return;let eligible=true;try{eligible=localStorage.getItem('omnivert-email-subscribed')!=='true'&&Date.now()-Number(localStorage.getItem(offerKey)||0)>7*24*60*60*1000}catch{}if(eligible)offerTimer=setTimeout(()=>{if(!document.querySelector('dialog[open]')&&!document.hidden){open('waitlist');markOfferSeen();}},2200);}scheduleOffer();document.addEventListener('visibilitychange',scheduleOffer);}

$('#nav-shade')?.addEventListener('click',closeMega);
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMega();if(e.target.matches('[data-tab]')&&['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const tabs=$$('[data-tab]');let i=tabs.indexOf(e.target);i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;filter(tabs[i].dataset.tab);tabs[i].focus()}});
document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;
if(b.hasAttribute('data-model-toggle')){e.preventDefault();const active=b.closest('.card-media').classList.toggle('show-model');b.setAttribute('aria-pressed',String(active));b.setAttribute('aria-label',active?'Show product view':'Show model view');b.textContent=active?'PRODUCT':'ON MODEL';return;}
if(b.dataset.open){e.preventDefault();open(b.dataset.open)}
if(b.dataset.mega){const was=b.getAttribute('aria-expanded')==='true';closeMega();if(!was){headerPosition();$('#mega').hidden=false;$('#mega').dataset.mode=b.dataset.mega;$('#nav-shade').hidden=false;b.setAttribute('aria-expanded','true')}}
if(b.dataset.info){e.preventDefault();infoFor(b.dataset.info)}
if(b.dataset.tab){filter(b.dataset.tab)}
if(b.dataset.category){e.preventDefault();filter(b.dataset.category,'',true)}
if(b.dataset.query){filter('All',b.dataset.query,true)}
if(b.dataset.quick!==undefined){e.preventDefault();showProduct(b.dataset.quick)}
if(b.dataset.detail!==undefined){if(shopify){e.preventDefault();showProduct(b.dataset.detail,true)}else{e.preventDefault();location.href='?product='+b.dataset.detail}}
if(b.dataset.liveQuick){showLiveProduct(b.dataset.liveQuick)}
if(b.dataset.size){selected=b.dataset.size;$$('[data-size]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#size-label').textContent=selected}
if(b.dataset.qty){qty=Math.min(99,Math.max(1,qty+Number(b.dataset.qty)));$('#quantity').textContent=qty}
if(b.hasAttribute('data-add-concept')){if(shopify){info('Concept preview','This is a design concept, not a live Shopify product. Choose an actual product collection in the theme editor to enable purchases.');return;}const line=cart.find(x=>x.id===activeProduct.id&&x.size===selected);if(line)line.qty=Math.min(99,line.qty+qty);else cart.push({id:activeProduct.id,size:selected,qty});persist();open('cart')}
if(b.hasAttribute('data-remove')){cart.splice(Number(b.dataset.remove),1);persist();demoCart()}
if(b.dataset.cartDelta){const i=Number(b.dataset.line);cart[i].qty=Math.min(99,cart[i].qty+Number(b.dataset.cartDelta));cart=cart.filter(x=>x.qty>0);persist();demoCart()}
if(b.hasAttribute('data-demo-checkout'))info('Preview checkout','Your demo cart works, but no payment can be taken yet. After Shopify is connected, this step will open Shopify’s secure checkout.');
if(b.dataset.slide){const track=document.getElementById(b.dataset.target);track.scrollBy({left:Number(b.dataset.slide)*track.clientWidth*.8,behavior:reduced?'instant':'smooth'})}
if(b.dataset.liveVariant){selected=b.dataset.liveVariant;const v=liveProduct.variants.find(x=>String(x.id)===selected);$$('[data-live-variant]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#live-price').textContent=money(v.price)}
if(b.hasAttribute('data-add-live')){b.disabled=true;try{const r=await fetch(root+'cart/add.js',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:[{id:Number(selected),quantity:qty}]})});const result=await r.json();if(!r.ok)throw Error(result.description||'Unable to add this item.');open('cart')}catch(err){$('#product-error').textContent=err.message}finally{b.disabled=false}}
if(b.dataset.liveLine){b.disabled=true;try{const r=await fetch(root+'cart/change.js',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({line:Number(b.dataset.liveLine),quantity:Number(b.dataset.liveQty)})});if(!r.ok)throw Error();await renderCart()}catch{info('Cart update failed','Please try again or open the cart page.')}finally{b.disabled=false}}
});
if(!shopify)updateCount();
const initial=new URLSearchParams(location.search).get('product');if(initial!==null&&!shopify&&catalog.some(p=>String(p.id)===initial)){showProduct(initial,true);const content=$('#quick-content').innerHTML;$('#quick').close();$('#quick-content').innerHTML='';$('#main').innerHTML='<div class="product-detail-page"><a class="back-link" href="/">← BACK TO COLLECTION</a>'+content+'</div>';document.title=catalog.find(p=>String(p.id)===initial).name.toUpperCase()+' — OMNIVERT';}
})();
